### ISSUE TITLE
Integration ObjC Example does not run

### ISSUE THREAD

**Issue by flyric123** [Bluedot-Innovation/PointSDK-MinimalIntegrationExample-iOS#1]
Hi, we just downloaded the example and built the Objective-C version. It built fine. However, when we launched the app on a simulator, the example app crashed at the splash screen (a white screen), and we found the following error in the output window:
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/nei/Library/Developer/CoreSimulator/Devices/14AC942A-66F8-479F-81A6-8881786BD893/data/Containers/Bundle/Application/3AD293A4-260B-4852-8E20-C5C0DE0313E3/PointSDK Objc Minimal.app/Frameworks/BDPointSDK.framework/BDPointSDK
  Reason: image not found

XCode version: 10.2.1
MacOS version: 10.14.4
Simulator: iPhone 6 on iOS 12.2

Any ideas on how to get the example running on our system?
Thx!

**Comment by andrew-stirling** [comment]
Duplicate: https://github.com/Bluedot-Innovation/PointSDK-iOS/issues/2
